# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  traefik:
    image: traefik:v3.5
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik.yml:/traefik.yml:ro
      - ./traefik_dynamic.yml:/traefik_dynamic.yml:ro
      - ./certificate.pem:/certificate.pem:ro
      - ./certificate-key.pem:/certificate-key.pem:ro
    command:
      #- --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.file.filename=/traefik_dynamic.yml
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.options=default
    networks:
      - proxy
    labels:
      - traefik.enable=true
      #- traefik.http.routers.mydashboard.rule=Host(`traefik.localhost`)
      #- traefik.http.routers.mydashboard.service=api@internal
      #- traefik.http.routers.mydashboard.middlewares=myauth
      #- traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$12$$eg1aOPa9ukKEyo2K.7ZvLeZh7tLUTpV/V88il8.Pzr00hQPr4JYLO
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:15
    networks:
      wireguard:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      proxy:
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      - traefik.enable=true
      - traefik.http.routers.wireguard.rule=Host(`wireguard.localhost`) || Host(`vpn.nearata.com`)
      - traefik.http.services.wireguard.loadbalancer.server.port=51821
      - traefik.http.routers.wireguard.middlewares=myauth
      - traefik.http.middlewares.myauth.basicauth.users=admin:$$2y$$12$$eg1aOPa9ukKEyo2K.7ZvLeZh7tLUTpV/V88il8.Pzr00hQPr4JYLO
    environment:
      # https://wg-easy.github.io/wg-easy/latest/advanced/config/optional-config/
      - DISABLE_IPV6=true

networks:
  proxy:
  wireguard:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64

volumes:
  etc_wireguard:
